#!/bin/bash
clear
echo "Hi, I'm Sphinx."
sleep 1
if [ $(id -u) -eq 0 ]; then
    echo "You are running as the root user."
else
    echo "You are not running as the root user."
    echo "Can we elevate to root user? Just type your password."
    su root -c efibootmgr 
fi
sleep 2
clear
while true; do
    efibootmgr
    echo ""
    echo "Please Choose Here:"
    echo "A. Delete Bootable OS"
    echo "B. Edit BootOrder"
    echo "C. Create a new boot entry"
    echo "D. Exit"
    read -p "Option: " choice
    choice=${choice^^}

    case $choice in
        A)
            clear
            efibootmgr
            echo ""
            read -p "Choose what to delete number only Boot(0000): " deleteboot
            deleteboot=${deleteboot^^}
            clear
            efibootmgr | grep "$deleteboot"
            echo "We're goin' to delete this boot entry..."
            read -p "Are you sure you want to delete this boot entry (Y|N): " option
            option=${option^^}
            while true; do
                case $option in
                    "Y" | "YES")
                        efibootmgr -B --bootnum $deleteboot
                        clear
                        efibootmgr | grep "BootOrder"
                        efibootmgr | grep "*"
                        echo ""
                        echo "Deleted."
                        echo "exiting..."
                        sleep 5
                        clear
                        exit
                        break
                    ;;
                    "N" | "NO")
                        clear
                        sleep 1
                        echo "Exiting, Thankyou."
                        sleep 2
                        exit
                        break
                    ;;
                    *)
                    echo "Invalid Option, Please type Yes or No."
                    ;;
                esac
            done
            break
            ;;
        B)
            clear
            echo "Editing BootOrder..."
            sleep 2
            clear
            echo "Here's the current Boot Order:"
            echo ""
            efibootmgr | grep "BootOrder" | sed 's/\(.*\)/\x1b[38;5;217m\1\x1b[0m/'
            efibootmgr | grep "*"
            echo ""
            echo "Please Input Number Only!!"
            read -p "Here's the needed order 'n' means number(nnnn,nnnn,nnnn,nnnn): " bootorder
            sleep 2
            clear
            while true; do
                efibootmgr | grep "BootOrder"
                efibootmgr | grep "*"
                echo "We're goin' to change the boot order based on your input."
                light_pink=$(tput setaf 225)
                reset_color=$(tput sgr0)
                echo "${light_pink}New BootOrder:($bootorder)${reset_color}"
                read -p "want to proceed? (Y|N): " anotheropt
                anotheropt=${anotheropt^^}
                case $anotheropt in
                    "Y" | "YES")
                    echo "We're now going to change your Boot Order..."
                    efibootmgr -o $bootorder
                    sleep 2
                    clear
                    efibootmgr --save
                    echo "Done."
                    break
                    exit
                    ;;

                    "N" | "NO")
                    echo "We're NOT going to change your Boot Order."
                    sleep 2
                    clear
                    echo "We cancelled to change your boot order."
                    break
                    exit
                    ;;

                    *)
                    clear
                    echo "Invalid Option, Please type Yes or No."
                    echo ""
                    ;;
                esac
                    
            done


            break
            ;;
        C)
            echo "Creating a new boot entry..."
            break
            ;;
        D)
            echo "Exiting..."
            break
            ;;
        *)
            clear
            echo "Invalid option. Please choose A, B, C, or D."
            echo ""
            ;;
    esac
done


